services:
  kestra:
    build: .
    image: kestra/kestra:latest
    container_name: kestra
    user: "0:0"
    environment:
      DOCKER_HOST: tcp://host.docker.internal:2375  # Windows için TCP bağlantısı
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: h2
          queue:
            type: memory
          storage:
            type: local
            local:
              basePath: /app/storage
          tasks:
            tmp-dir:
              path: /app/tmp
          plugins:
            repositories:
              - id: central
                type: maven
                url: https://repo.maven.apache.org/maven2
            definitions:
              - io.kestra.plugin.core:core:latest
              - io.kestra.plugin.scripts:python:1.3.4
              - io.kestra.plugin.http:http:latest
      KESTRA_TASKS_TMP_DIR_PATH: /app/tmp
    ports:
      - "8080:8080"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock  # Windows path formatı
      - C:/Users/ayhan/.dbt:/app/.dbt
      - C:/Users/ayhan/kestra/plugins:/app/plugins
      - C:/Users/ayhan/kestra/workflows:/app/workflows
      - C:/Users/ayhan/kestra/storage:/app/storage
      - C:/Users/ayhan/kestra/tmp:/app/tmp
      - C:/Users/ayhan/WeatherPipeline/dbt_weather:/app/workflows/dbt_project
      - C:/Users/ayhan/.google/my-creds.json:/app/.dbt/my-creds.json
    command: server standalone
