services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: h2
          queue:
            type: memory
          storage:
            type: local
            local:
              basePath: /app/storage
          plugins:
            repositories:
              - id: central
                type: maven
                url: https://repo.maven.apache.org/maven2
            definitions:
              - io.kestra.plugin.core:core:latest
              - io.kestra.plugin.scripts:scripts:latest
              - io.kestra.plugin.http:http:latest
    ports:
      - "8080:8080"
    volumes:
      - ./plugins:/app/plugins
      - ./workflows:/app/workflows
      - ./storage:/app/storage
    command: server standalone